/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Datapath;

/**
 *
 * @author Huy
 */
public class GuideForm extends javax.swing.JFrame {

    /**
     * Creates new form GuideForm
     */
    public GuideForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrpGuide = new javax.swing.JScrollPane();
        txtaGuide = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hướng dẫn");
        setBounds(new java.awt.Rectangle(500, 250, 0, 0));
        setResizable(false);

        scrpGuide.setAutoscrolls(true);
        scrpGuide.getVerticalScrollBar().setValueIsAdjusting(true);
        scrpGuide.getVerticalScrollBar().setValue(0);

        txtaGuide.setEditable(false);
        txtaGuide.setBackground(new java.awt.Color(255, 102, 255));
        txtaGuide.setColumns(20);
        txtaGuide.setRows(5);
        txtaGuide.setText("Bước 1: Chọn một trong 8 lệnh add,sub,or,and,slt,beq,lw,sw bằng các \nbutton trong khung Chọn lệnh. Các block control cơ bản sẽ hiện ra bên \nkhung Mô phỏng.\n\nBước 2: Chỉnh tốc độ mô phỏng bằng cách kéo thanh slide Tốc độ. Hoặc có \nthể chỉnh song song trong lúc mô phỏng.\n\nBước 3: Chọn đầy đủ tất cả các thanh ghi cơ bản bên dưới chương trình \nhoặc điền vào số offset(chỉ cho tập lệnh I).\n\nBước 4: Chạy mô phỏng bằng 3 cách: \n- Bấm vào Button mô phỏng trong khung Điều khiển\n- Bấm phím tắt F5 để mô phỏng\n- Bấm vào Menu phía trên chọn Trạng Thái -> Mô phỏng\nChương trình sẽ mô phỏng lại đường đi Datapath đơn chu kì của lệnh mà \nngười dùng chọn. Các lệnh cũng sẽ được chuyển đổi qua mã nhị phân và \nthập lục phân ở dưới chương trình.\n\nTrong khi chương trình đang mô phỏng, người dùng có thể:\n- Tạm dừng mô phỏng bằng 3 cách:\n+ Bấm vào Button Dừng lại trong khung Điều khiển\n+ Bấm phím tắt F7\n+ Bấm vào Menu phía trên chọn Trạng Thái -> Dừng\n- Và tiếp tục mô phỏng bằng 3 cách:\n+ Bấm vào Button Tiếp tục trong khung Điều khiển\n+ Bấm phím tắt F6\n+ Bấm vào Menu phía trên chọn Trạng Thái -> Tiếp tục\n- Khi đang tạm dừng, có thể quay lùi lại hoặc bấm qua các bước mô phỏng \nbằng cách sử dụng các Button có icon(<),(>)\n- Trở về bước ban đầu của tập lệnh và tạm dừng mô phỏng bằng cách bấm \nButton Clear.\n- Reset hết tất cả mọi thứ và trở về trạng thái nguyên thủy bằng cách \nbấm Button Reset.\n");
        scrpGuide.setViewportView(txtaGuide);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpGuide, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrpGuide, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void StartGuideForm() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuideForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuideForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuideForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuideForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuideForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrpGuide;
    private javax.swing.JTextArea txtaGuide;
    // End of variables declaration//GEN-END:variables
}
