/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pipeline;

/**
 *
 * @author Huy
 */
public class GuideForm extends javax.swing.JFrame {

    /**
     * Creates new form GuideForm
     */
    public GuideForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hướng dẫn");
        setBounds(new java.awt.Rectangle(500, 250, 0, 0));
        setResizable(false);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 51, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Bước 1: Chọn tối đa 5 lệnh bất kì trong số 7 nút lệnh Add,Sub,\nSlt,And,Or,Lw,Sw để thêm lệnh vào bảng lệnh bên trái chương \ntrình. \n\nBước 2: Chọn đầy đủ tất cả các thanh ghi cơ bản cho các lệnh\nđã được đưa vào bảng lệnh.\n\nBước 4: Chạy mô phỏng bằng 3 cách: \n- Bấm vào Button mô phỏng trong khung Điều khiển\n- Bấm phím tắt F5 để mô phỏng\n- Bấm vào Menu phía trên chọn Lệnh -> Bắt đầu\nChương trình sẽ mô phỏng lại đường đi Pipeline và thể hiện\ncác đụng độ mà các lệnh của người dùng gặp phải với nhau\ntheo cách trong slide môn Kiến trúc Máy Tính. \nChương trình cũng sẽ tính số chu kì của các lệnh đã chạy \ntrong bảng lệnh\n\nNgoài ra, người dùng có thể:\n- Xóa các lệnh bằng cách ấn Button Xóa bên cạnh các thẻ\nlệnh trong bảng lệnh\n- Thêm lệnh bằng 3 cách\n+ Bấm vào Button Lệnh dưới góc trái phía dưới\n+ Bấm phím tắt Ctrl + 1 để thêm lệnh Add, Ctrl + 2 để thêm\nlệnh Sub, Ctrl + 3 để thêm lệnh Sw, Ctrl + 4 để thêm lệnh Lw,\nCtrl + 5 để thêm lệnh Or, Ctrl + 6 để thêm lệnh And, Ctrl + 7 để\nthêm lệnh Slt.\n+ Bấm vào Menu phía trên chọn Lệnh -> (Tên lệnh)\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void StartGuideForm() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuideForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuideForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuideForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuideForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuideForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
